wordpress:
  build: .
  ports:
    - 80:80
  links:
    - db:mysql
  volumes:
    - ./wordpress:/var/www/html
  dns: 208.67.222.222
  environment:
    WP_VERSION: 4.6.1

db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: password
